/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Mar 23 00:31:21 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TypeHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.TypeHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/z3/st24ttp10vxbf_1j6tstwvy80000gn/T/"); 
    java.lang.System.setProperty("user.country", "CA"); 
    java.lang.System.setProperty("user.dir", "/Users/anthonykap/Documents/GitHub/commons-cli"); 
    java.lang.System.setProperty("user.home", "/Users/anthonykap"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "anthonykap"); 
    java.lang.System.setProperty("user.timezone", "America/Toronto"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TypeHandler_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.cli.Converter",
      "org.apache.commons.text.lookup.StringLookup",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.text.lookup.ResourceBundleStringLookup",
      "org.apache.commons.cli.TypeHandler"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TypeHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.FileSystem",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.apache.commons.text.StrLookup$MapStrLookup",
      "org.apache.commons.text.StrLookup",
      "org.apache.commons.text.StrLookup$SystemPropertiesStrLookup",
      "org.apache.commons.text.similarity.JaroWinklerDistance",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.EmptyFileFilter",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "org.apache.commons.text.lookup.ResourceBundleStringLookup",
      "org.apache.commons.text.lookup.UrlStringLookup",
      "org.junitpioneer.jupiter.cartesian.CartesianFactoryArgumentsProvider",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.text.similarity.JaccardSimilarity",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "org.apache.commons.cli.help.TextStyle",
      "org.apache.commons.text.similarity.IntersectionSimilarity",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction",
      "org.mockito.internal.creation.bytebuddy.StackWalkerChecker",
      "org.junitpioneer.jupiter.params.RangeSourceArgumentsProvider",
      "org.apache.commons.text.lookup.XmlEncoderStringLookup",
      "org.junitpioneer.jupiter.json.JsonClasspathSourceArgumentsProvider",
      "org.apache.commons.text.lookup.DnsStringLookup",
      "org.apache.commons.io.serialization.WildcardClassNameMatcher",
      "org.junitpioneer.jupiter.CartesianValueArgumentsProvider",
      "org.apache.commons.io.filefilter.WildcardFileFilter$1"
    );
  }
}
