/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 23 00:22:13 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.BufferedWriter;
import java.io.ByteArrayOutputStream;
import java.io.CharArrayWriter;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileDescriptor;
import java.io.ObjectOutputStream;
import java.io.OutputStreamWriter;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.io.PipedReader;
import java.io.PipedWriter;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.io.UnsupportedEncodingException;
import java.net.URI;
import java.nio.charset.Charset;
import java.nio.charset.CharsetEncoder;
import java.util.Comparator;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.cli.Options;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockFileOutputStream;
import org.evosuite.runtime.mock.java.io.MockFileWriter;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.evosuite.runtime.mock.java.io.MockPrintWriter;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HelpFormatter_ESTest extends HelpFormatter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "H";
      helpFormatter0.rtrim("H");
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "H");
      StringBuffer stringBuffer1 = helpFormatter0.renderWrappedText(stringBuffer0, (-3218), (-1147692044), "H");
      helpFormatter0.renderWrappedText(stringBuffer1, (-1147692044), 19, ")*K)}(TxhRL/.7har");
      // Undeclared exception!
      try { 
        helpFormatter0.findWrapPos(" ", 19, (-3218));
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = new StringWriter(1);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(stringWriter1, false);
      stringWriter1.append('[');
      helpFormatter1.printUsage((PrintWriter) mockPrintWriter0, (-1177), "cmdLineSyntax not provided");
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      stringWriter1.append((CharSequence) "\n");
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter1.getSyntaxPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 468, "initialList", "arg", options0, 1, 1, "org.apache.commons.io.filefilter.IOFileFilter", true);
      helpFormatter1.getOptPrefix();
      Option option0 = new Option("arg", false, "initialList");
      options0.addOption(option0);
      helpFormatter1.printHelp("usage: ", "initialList", options0, "initialList", true);
      helpFormatter0.getArgName();
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringBuffer stringBuffer0 = new StringBuffer("--");
      int int0 = 459;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) null, 657, "Bad XML key format '%s'; the expected format is 'DocumentPath:XPath'.", "", (Options) null, 2466, 459, "Bad XML key format '%s'; the expected format is 'DocumentPath:XPath'.", false);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.defaultArgName = null;
      helpFormatter0.getWidth();
      helpFormatter0.getWidth();
      helpFormatter0.getArgName();
      helpFormatter0.getSyntaxPrefix();
      helpFormatter0.createPadding(3);
      Options options0 = new Options();
      options0.getOptions();
      helpFormatter0.renderOptions((StringBuffer) null, 74, options0, 35, 410);
      PipedInputStream pipedInputStream0 = new PipedInputStream(1);
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream(pipedInputStream0);
      MockPrintStream mockPrintStream0 = new MockPrintStream(pipedOutputStream0, true);
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(mockPrintStream0);
      helpFormatter0.appendWrappedText(outputStreamWriter0, (-1177), 74, (String) null);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(charArrayWriter0);
      PrintWriter printWriter0 = mockPrintWriter0.append((CharSequence) " ");
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(printWriter0, (-1006), "org.apache.commons.io.file.StandardDeleteOption", (String) null, options0, (-1006), (-856), "LhO^q<SN\"?9gwHfF<", false);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, "-");
      helpFormatter0.defaultWidth = 16;
      helpFormatter0.renderWrappedText((StringBuffer) null, (-735), 9, ".OKI|&'oA6`R@3~/d");
      int int0 = 18;
      // Undeclared exception!
      try { 
        helpFormatter0.renderWrappedText((StringBuffer) null, 120, 18, ".OKI|&'oA6`R@3~/d");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "`RmJ>uQJ";
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("`RmJ>uQJ");
      Options options0 = new Options();
      helpFormatter0.printOptions(mockPrintWriter0, (-564), options0, 0, 0);
      helpFormatter0.defaultSyntaxPrefix = "]";
      helpFormatter0.getOptPrefix();
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter0.defaultWidth = 1;
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setPrintWriter(mockPrintWriter0);
      helpFormatter_Builder2.setShowDeprecated(true);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowDeprecated(false);
      HelpFormatter helpFormatter1 = helpFormatter_Builder3.get();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/Users/anthonykap/Documents/GitHub/commons-cli");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "<");
      helpFormatter0.printHelp("5Fa/X:g7wBq2$I=", options0);
      int int0 = 3582;
      helpFormatter1.setDescPadding(int0);
      helpFormatter1.printHelp(string0, options0);
      helpFormatter1.getArgName();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, "Description");
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      MockFile mockFile0 = new MockFile("", "7/zU=99#'%[28y!AY");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 793, (String) null, (String) null, (Options) null, 793, 793, "7/zU=99#'%[28y!AY", true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      int int0 = (-522);
      helpFormatter0.defaultDescPad = (-522);
      Comparator<Option> comparator0 = helpFormatter0.optionComparator;
      helpFormatter0.optionComparator = comparator0;
      int int1 = 14;
      helpFormatter0.findWrapPos("", 14, 10);
      helpFormatter0.getLeftPadding();
      helpFormatter0.rtrim("&X>J0TLw");
      helpFormatter0.getArgName();
      Option option0 = new Option("arg", true, "-");
      option0.processValue("-");
      HelpFormatter.getDescription(option0);
      helpFormatter0.getNewLine();
      helpFormatter0.createPadding(14);
      Options options0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.appendOptions((BufferedWriter) null, (-1), (Options) null, 1393, 10);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getArgName();
      Options options0 = null;
      helpFormatter0.getLongOptPrefix();
      helpFormatter0.getDescPadding();
      Option option0 = new Option("UI3", " ");
      HelpFormatter.getDescription(option0);
      MockPrintWriter mockPrintWriter0 = null;
      try {
        mockPrintWriter0 = new MockPrintWriter("arg", "org.apache.commons.text.lookup.AbstractStringLookup");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(Throwable e) {
         //
         // org.apache.commons.text.lookup.AbstractStringLookup
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockPrintWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      helpFormatter0.setDescPadding(9);
      helpFormatter0.getWidth();
      helpFormatter0.rtrim((String) null);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setNewLine(">");
      HelpFormatter.builder();
      Options options0 = new Options();
      Options options1 = options0.addRequiredOption((String) null, "usage: ", true, "arg");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setRequired(true);
      optionGroup0.setRequired(true);
      options1.addOptionGroup(optionGroup0);
      options0.getOption("usage: ");
      helpFormatter0.setOptPrefix("|Uy%=,,YGKg*j>5>H");
      helpFormatter0.printHelp(">", ">", options0, " | ");
      helpFormatter0.getSyntaxPrefix();
      URI uRI0 = MockURI.aFTPURI;
      MockFile mockFile0 = null;
      try {
        mockFile0 = new MockFile(uRI0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // URI scheme is not \"file\"
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setOptPrefix("org.apache.commons.cli.HelpFormatter");
      Options options0 = new Options();
      Option option0 = new Option((String) null, "\n");
      option0.equals(helpFormatter0);
      Options options1 = options0.addOption(option0);
      options0.getMatchingOptions("org.apache.commons.cli.HelpFormatter");
      options0.hasOption("org.apache.commons.cli.HelpFormatter");
      helpFormatter0.printHelp("org.apache.commons.cli.HelpFormatter", options0);
      helpFormatter0.setLongOptSeparator("m9bNel+c5+KHh");
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/Users/anthonykap/Documents/GitHub/commons-cli");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      String string0 = "h6DHBkdOtTdmz";
      helpFormatter0.printHelp((-1), "m9bNel+c5+KHh", "m9bNel+c5+KHh", options1, "h6DHBkdOtTdmz", false);
      int int0 = 1865;
      String string1 = "org.apache.commons.text.lookup.DnsStringLookup";
      String string2 = "Fcn*ce4#kP^trPi";
      helpFormatter0.printHelp(1865, "org.apache.commons.text.lookup.DnsStringLookup", "Fcn*ce4#kP^trPi", options1, "!j4i.'-|}h", false);
      options1.hasShortOption("-");
      MockFile mockFile0 = new MockFile("arg");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      String string3 = null;
      int int1 = (-271);
      int int2 = 0;
      helpFormatter0.getWidth();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, (-271), ";'6G+A~Ecqb", "m9bNel+c5+KHh", options1, 8, (-1), ";'6G+A~Ecqb", true);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.get();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      PipedOutputStream pipedOutputStream0 = new PipedOutputStream();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(pipedOutputStream0);
      Locale locale0 = Locale.UK;
      helpFormatter0.appendWrappedText((StringBuffer) null, 0, 1, "aewZ#eb");
      Object[] objectArray0 = new Object[2];
      objectArray0[0] = (Object) helpFormatter_Builder1;
      objectArray0[1] = (Object) helpFormatter_Builder1;
      PrintWriter printWriter0 = mockPrintWriter0.format(locale0, "", objectArray0);
      helpFormatter0.printUsage(printWriter0, 3, "-");
      Function<Option, String> function1 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function1);
      helpFormatter0.printHelp(0, "Invalid text", "<", options0, "2;uVo;v");
      MockPrintWriter mockPrintWriter1 = null;
      try {
        mockPrintWriter1 = new MockPrintWriter((File) null, "-");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(Throwable e) {
         //
         // -
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockPrintWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = stringWriter0.append((CharSequence) "arg");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(stringWriter1, false);
      stringWriter1.append('Z');
      helpFormatter1.printUsage((PrintWriter) mockPrintWriter0, (-1177), "cmdLineSyntax not provided");
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      stringWriter1.append((CharSequence) "\n");
      HelpFormatter.builder();
      String string0 = helpFormatter1.getSyntaxPrefix();
      int int0 = 468;
      String string1 = "initialList";
      helpFormatter1.printUsage((PrintWriter) mockPrintWriter0, 1, "-");
      Options options0 = new Options();
      String string2 = "org.apache.commons.io.filefilter.IOFileFilter";
      boolean boolean0 = true;
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, int0, string1, helpFormatter1.DEFAULT_ARG_NAME, options0, helpFormatter1.defaultLeftPad, helpFormatter1.defaultLeftPad, string2, boolean0);
      helpFormatter1.printHelp(helpFormatter0.DEFAULT_LONG_OPT_PREFIX, options0, boolean0);
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter1.getOptPrefix();
      boolean boolean1 = true;
      helpFormatter1.printHelp(string0, string1, options0, string1, boolean1);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      String string0 = "B,VwvPhA}!Sg";
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("B,VwvPhA}!Sg");
      String string1 = " {Uj}";
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) " {Uj}";
      objectArray0[1] = (Object) helpFormatter_Builder0;
      objectArray0[2] = (Object) helpFormatter_Builder1;
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(" {Uj}", "org.apache.commons.text.lookup.UrlDecoderStringLookup", options0, " {Uj}", true);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      String string0 = ">";
      MockFile mockFile0 = new MockFile(">");
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFile0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockPrintStream0);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setPrintWriter(mockPrintWriter0);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(true);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      helpFormatter0.rtrim(">");
      helpFormatter_Builder3.setShowSince(false);
      helpFormatter0.rtrim(">");
      int int0 = (-1806);
      String string1 = "5ON!hH)2DEgUF~f";
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, "");
      helpFormatter_Builder3.setShowDeprecated(function0);
      // Undeclared exception!
      try { 
        helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, (-1806), "5ON!hH)2DEgUF~f", (Options) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printHelp(helpFormatter0.defaultLeftPad, helpFormatter1.defaultOptPrefix, helpFormatter0.DEFAULT_LONG_OPT_PREFIX, options0, helpFormatter1.defaultArgName);
      StringBuffer stringBuffer0 = null;
      int int0 = 0;
      Options options1 = new Options();
      int int1 = 39;
      helpFormatter1.setLeftPadding(helpFormatter0.DEFAULT_LEFT_PAD);
      int int2 = 0;
      helpFormatter1.renderOptions(stringBuffer0, int0, options1, int1, int2);
      String string0 = ">7y4l9";
      helpFormatter0.setArgName(string0);
      int int3 = helpFormatter0.getWidth();
      PrintWriter printWriter0 = null;
      int int4 = 0;
      helpFormatter0.printWrapped(printWriter0, int4, helpFormatter1.DEFAULT_ARG_NAME);
      int int5 = 77;
      helpFormatter0.findWrapPos(helpFormatter1.DEFAULT_LONG_OPT_PREFIX, int5, int5);
      HelpFormatter.builder();
      int int6 = 0;
      helpFormatter0.printUsage(printWriter0, int6, helpFormatter1.defaultLongOptPrefix, options1);
      boolean boolean0 = true;
      helpFormatter1.printHelp(helpFormatter0.DEFAULT_LONG_OPT_PREFIX, helpFormatter0.DEFAULT_ARG_NAME, options1, helpFormatter0.defaultNewLine, boolean0);
      String string1 = "";
      helpFormatter0.printWrapped(printWriter0, int5, int2, string1);
      int int7 = 314;
      String string2 = "";
      boolean boolean1 = false;
      helpFormatter1.printHelp(printWriter0, int7, helpFormatter0.defaultOptPrefix, helpFormatter0.DEFAULT_LONG_OPT_SEPARATOR, options1, int3, helpFormatter0.DEFAULT_WIDTH, string2, boolean1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/var/folders/z3/st24ttp10vxbf_1j6tstwvy80000gn/T");
      FileSystemHandling.setPermissions(evoSuiteFile0, true, false, true);
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp(3, "[ARG...]", (String) null, options0, "[ARG...]", false);
      helpFormatter0.getLeftPadding();
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      File file0 = MockFile.createTempFile("arg", " ");
      helpFormatter0.defaultOptPrefix = "";
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, (-1634), "");
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp((-1634), "[ARG...]", (String) null, options0, "[ARG...]", false);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter_Builder0.get();
      String string0 = "";
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(9, "-", "", options0, "arg");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.renderOptions((StringBuffer) null, 0, options0, 0, 0);
      // Undeclared exception!
      try { 
        options0.addRequiredOption("", "", false, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringWriter stringWriter0 = new StringWriter();
      boolean boolean0 = false;
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(stringWriter0, false);
      Object[] objectArray0 = new Object[2];
      objectArray0[0] = (Object) helpFormatter0;
      objectArray0[1] = (Object) stringWriter0;
      mockPrintWriter0.printf("arg", objectArray0);
      String string0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "";
      helpFormatter0.defaultLongOptPrefix = "";
      StringBuffer stringBuffer0 = new StringBuffer(714);
      int int0 = 5758;
      // Undeclared exception!
      try { 
        helpFormatter0.renderWrappedText(stringBuffer0, 5758, 32, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("l%;l89[b+wft&G", "l%;l89[b+wft&G", (Options) null, "gu");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowSince(true);
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(3420);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(byteArrayOutputStream0, true);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setPrintWriter(mockPrintWriter0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      StringBuffer stringBuffer0 = new StringBuffer(1);
      helpFormatter0.appendWrappedText(stringBuffer0, 3420, 2393, "/vuF");
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(2393, "y!1N+\"k:6j", "i#JlK?ft.c,~1_t", (Options) null, "Xk{wt(iZ*8n!r2Lu", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(" for removal");
      Object[] objectArray0 = new Object[5];
      objectArray0[0] = (Object) helpFormatter_Builder0;
      objectArray0[1] = (Object) helpFormatter0;
      objectArray0[2] = (Object) helpFormatter0;
      objectArray0[3] = (Object) helpFormatter0;
      objectArray0[4] = (Object) " for removal";
      PrintWriter printWriter0 = mockPrintWriter0.printf("-", objectArray0);
      helpFormatter_Builder0.setPrintWriter(printWriter0);
      Options options0 = new Options();
      helpFormatter0.printHelp("X{Gu]48XK", "0}", options0, "org.apache.commons.cli.HelpFormatter$Builder");
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, (-364), "R$h:@G4", "", options0, 1, 1, "", true);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder2.get();
      MockFile mockFile0 = new MockFile("--");
      mockFile0.setWritable(false);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      mockPrintWriter0.println('@');
      mockPrintWriter0.println((Object) helpFormatter_Builder0);
      mockFile0.setExecutable(false);
      helpFormatter_Builder0.setShowDeprecated(false);
      helpFormatter0.printWrapped((PrintWriter) mockPrintWriter0, 44, 371, "");
      helpFormatter_Builder0.setShowDeprecated(true);
      helpFormatter0.setLongOptSeparator("#629");
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder2.setShowDeprecated(function0);
      helpFormatter0.createPadding(0);
      HelpFormatter.builder();
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp("value must not be empty", options0);
      MockFileWriter mockFileWriter0 = new MockFileWriter(" | ");
      // Undeclared exception!
      try { 
        helpFormatter0.appendWrappedText((OutputStreamWriter) mockFileWriter0, 371, 1083, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLongOptPrefix((String) null);
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = stringWriter0.append('c');
      StringWriter stringWriter2 = stringWriter1.append((CharSequence) "arg");
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.appendOptions(stringWriter2, (-863), options0, 0, (-863));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = " [bundleName=";
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(" [bundleName=");
      int int0 = (-198);
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions(mockPrintWriter0, (-198), options0, (-198), (-3691));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockFileWriter mockFileWriter0 = new MockFileWriter("arg", false);
      boolean boolean0 = true;
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileWriter0, true);
      MockPrintWriter mockPrintWriter1 = new MockPrintWriter(mockPrintWriter0);
      helpFormatter0.printWrapped((PrintWriter) mockPrintWriter1, 75, 75, "dqL^M~BAJ!'L}");
      helpFormatter0.getDescPadding();
      String string0 = "E";
      Options options0 = new Options();
      helpFormatter0.printHelp("dqL^M~BAJ!'L}", "E", options0, "dqL^M~BAJ!'L}", false);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 75, "E", "]Qx!uQ3", options0, (-615), 0, (String) null);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = null;
      helpFormatter0.setOptPrefix((String) null);
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printOptions((PrintWriter) null, 499, options0, 499, 0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      int int0 = 217;
      String string0 = "";
      String string1 = "[CG,[3P]T3xhK1B`7}*";
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(217, "", "[CG,[3P]T3xhK1B`7}*", options0, "]");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      File file0 = MockFile.createTempFile("usage: ", "^2B$G|;PV[<P");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      BufferedWriter bufferedWriter0 = new BufferedWriter(mockPrintWriter0);
      MockPrintWriter mockPrintWriter1 = new MockPrintWriter(bufferedWriter0);
      Options options0 = new Options();
      mockPrintWriter0.println(0L);
      bufferedWriter0.append((CharSequence) "\n");
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter1, 32, "^2B$G|;PV[<P", "^2B$G|;PV[<P", options0, 32, 32, "^2B$G|;PV[<P", false);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(3028, "", "rwQPF&0&r%rx<WPK", options0, (String) null, false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("q1");
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, (-1610), "q1", ".b", options0, 6398, (-1610), "V6Gzd.r|/3", false);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      // Undeclared exception!
      try { 
        helpFormatter0.findWrapPos((String) null, 2004, 351608024);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLeftPadding((-186));
      helpFormatter0.setLongOptPrefix("|4X\"=,8?d");
      MockFile mockFile0 = new MockFile("Exactly one type of input must be provided in the @", "?h`+$z`8A$y+t@*i");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      MockPrintWriter mockPrintWriter1 = new MockPrintWriter(mockPrintWriter0, false);
      Locale locale0 = Locale.TRADITIONAL_CHINESE;
      Locale.getISOCountries();
      Object[] objectArray0 = new Object[0];
      PrintWriter printWriter0 = mockPrintWriter1.printf(locale0, "_x'nKRE\"7z2", objectArray0);
      helpFormatter0.printUsage(printWriter0, 116909544, "default locale: ");
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(false);
      Function<Option, String> function1 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder2.setShowDeprecated(function1);
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("Exactly one type of input must be provided in the @", "Uijv+xUrp3%_", options0, "/M#R9|AH6k#-B.");
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((String) null, options0, true);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      // Undeclared exception!
      try { 
        HelpFormatter.getDescription((Option) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Option option0 = new Option("0", "");
      option0.clearValues();
      HelpFormatter.getDescription(option0);
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getDescPadding();
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getOptionComparator();
      helpFormatter0.getLongOptSeparator();
      Options options0 = null;
      boolean boolean0 = true;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(" ", " ", (Options) null, " ", true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setOptPrefix("org.apache.commons.cli.HelpFormatter");
      Options options0 = new Options();
      Option option0 = new Option((String) null, "\n");
      option0.equals(helpFormatter0);
      Options options1 = options0.addOption(option0);
      options0.getMatchingOptions("org.apache.commons.cli.HelpFormatter");
      options0.hasOption("org.apache.commons.cli.HelpFormatter");
      helpFormatter0.printHelp("org.apache.commons.cli.HelpFormatter", options0);
      helpFormatter0.setLongOptSeparator("org.apache.commons.text.similarity.CosineDistance");
      String string0 = "h6DHBkdOtTdmz";
      helpFormatter0.printHelp((-1), "org.apache.commons.text.similarity.CosineDistance", "org.apache.commons.text.similarity.CosineDistance", options1, "h6DHBkdOtTdmz", false);
      int int0 = 1865;
      String string1 = "Fcn*ce4#kP^trPi";
      helpFormatter0.printHelp(1865, "org.apache.commons.text.lookup.DnsStringLookup", "Fcn*ce4#kP^trPi", options1, "!j4i.'-|}h", false);
      MockFile mockFile0 = new MockFile("arg");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 1865, (String) null, "org.apache.commons.text.lookup.DnsStringLookup", options1, (-271), 0, "h6DHBkdOtTdmz");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter_Builder0.setShowSince(true);
      helpFormatter_Builder0.setShowDeprecated(true);
      boolean boolean0 = false;
      helpFormatter_Builder0.setShowDeprecated(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      int int0 = 1752;
      Options options0 = new Options();
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.optionComparator = comparator0;
      boolean boolean1 = false;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(1752, "RNjRkhw0f|=*:Z%", "RNjRkhw0f|=*:Z%", options0, "b}&sq=,.lOt<]/n", false);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      FileSystemHandling.appendLineToFile((EvoSuiteFile) null, ".BXGcb/");
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setLongOptSeparator(".BXGcb/");
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(3);
      helpFormatter0.appendWrappedText(charArrayWriter0, (-807), 14, ".BXGcb/");
      helpFormatter0.getWidth();
      helpFormatter0.getSyntaxPrefix();
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      File file0 = MockFile.createTempFile("vP1u[V&IIwU~{vfisbX", "usage: ");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setPrintWriter(mockPrintWriter0);
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.rtrim("n");
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(true);
      helpFormatter0.setOptPrefix("");
      StringBuffer stringBuffer0 = new StringBuffer();
      stringBuffer0.append((Object) helpFormatter_Builder2);
      Options options0 = new Options();
      helpFormatter0.renderOptions(stringBuffer0, 0, options0, 1450, 0);
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, "3V&'n/m)H11W(");
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultLongOptPrefix = "Invalid intersection of A and B: ";
      helpFormatter0.setWidth(0);
      helpFormatter0.createPadding(1443);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("!e3p@oT");
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setPrintWriter(mockPrintWriter0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter0.findWrapPos("!e3p@oT", 0, 0);
      MockFile mockFile0 = new MockFile("8:A8<", "/6XW[3iBDnF)");
      MockFileWriter mockFileWriter0 = new MockFileWriter(mockFile0, true);
      mockFile0.createNewFile();
      Options options0 = new Options();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("Since", false, "cmdLineSyntax not provided");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      options0.addOptionGroup(optionGroup1);
      mockFile0.setReadOnly();
      helpFormatter0.appendOptions((OutputStreamWriter) mockFileWriter0, 0, options0, 0, 2606);
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "";
      helpFormatter0.rtrim("");
      Options options0 = new Options();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option((String) null, (String) null);
      options0.addOption(option0);
      String string1 = "rp8@o\"Bs'y)P";
      Option option1 = null;
      try {
        option1 = new Option("rp8@o\"Bs'y)P", "--");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'rp8@o\"Bs'y)P' contains an illegal character : '@'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printHelp(5895, " | ", "2vLBiG6*n~}5~iuec,O", options0, " | ", false);
      StringBuffer stringBuffer0 = new StringBuffer();
      stringBuffer0.append(3);
      Option option0 = new Option("arg", "--", false, "LQ'I}H#e*/[");
      options0.addOption(option0);
      helpFormatter0.renderOptions(stringBuffer0, 5895, options0, 74, 74);
      helpFormatter0.setArgName("Ln~.';Rd(gE<J6vc");
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockFile mockFile0 = new MockFile("-", " ");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      PrintWriter printWriter0 = mockPrintWriter0.append('T');
      helpFormatter0.printWrapped(printWriter0, 0, "jGt3Za");
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("o^-Ykhv6rhM]~k:", options0);
      helpFormatter0.setArgName("");
      helpFormatter0.setLeftPadding(39);
      helpFormatter0.getLeftPadding();
      helpFormatter0.setDescPadding(39);
      MockPrintStream mockPrintStream0 = null;
      try {
        mockPrintStream0 = new MockPrintStream((File) null, "p/zH");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("Option '");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFileOutputStream0, false);
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setPrintWriter(mockPrintWriter0);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowSince(false);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowDeprecated(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      Charset charset0 = Charset.defaultCharset();
      CharsetEncoder charsetEncoder0 = charset0.newEncoder();
      OutputStreamWriter outputStreamWriter0 = new OutputStreamWriter(mockFileOutputStream0, charsetEncoder0);
      Options options0 = new Options();
      helpFormatter0.appendOptions(outputStreamWriter0, 9, options0, 9, 0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("-[M -z;;hF", "", options0, "");
      helpFormatter0.setLongOptSeparator("(=<%S");
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.getWidth();
      HelpFormatter helpFormatter1 = helpFormatter_Builder1.get();
      File file0 = MockFile.createTempFile("usage: ", "");
      MockPrintStream mockPrintStream0 = new MockPrintStream(file0);
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(mockPrintStream0);
      DataOutputStream dataOutputStream0 = new DataOutputStream(objectOutputStream0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(dataOutputStream0, true);
      objectOutputStream0.writeByte(1);
      mockPrintWriter0.write("", 3, 0);
      objectOutputStream0.reset();
      Options options0 = new Options();
      Options options1 = new Options();
      dataOutputStream0.close();
      options1.getOptions();
      options0.addOptions(options1);
      // Undeclared exception!
      try { 
        helpFormatter1.printHelp((PrintWriter) mockPrintWriter0, 0, (String) null, "\n", options0, 31, 3, "Options");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("-[M -z;;hF", "", options0, "");
      helpFormatter0.setLongOptSeparator("-[M -z;;hF");
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printHelp(138, "<", "<", options0, "<");
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      String string0 = "";
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.optionComparator = comparator0;
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", options0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "C7Kv1' ";
      int int0 = 531;
      helpFormatter0.setLeftPadding(531);
      Options options0 = new Options();
      File file0 = MockFile.createTempFile("org.apache.commons.cli.ParseException", "");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      char[] charArray0 = new char[8];
      charArray0[0] = ':';
      charArray0[1] = '^';
      charArray0[2] = 'j';
      charArray0[3] = ' ';
      charArray0[4] = 'H';
      charArray0[5] = 'H';
      charArray0[6] = 'K';
      charArray0[7] = '}';
      mockPrintWriter0.write(charArray0);
      // Undeclared exception!
      try { 
        helpFormatter0.printWrapped((PrintWriter) mockPrintWriter0, 0, (String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printWrapped((PrintWriter) null, 312, 0, "l3mm]R:HR'@t");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter();
      helpFormatter0.appendWrappedText(charArrayWriter0, 7, 61, "Description");
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.findWrapPos("-", 2004, 351608024);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(false);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowSince(false);
      HelpFormatter helpFormatter0 = helpFormatter_Builder2.get();
      StringBuffer stringBuffer0 = new StringBuffer(74);
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.renderOptions(stringBuffer0, (-2312), options0, 0, (-2589));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      File file0 = MockFile.createTempFile("arg", " ");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(file0);
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, (-1634), "");
      helpFormatter0.getOptPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp((-1634), "[ARG...]", (String) null, options0, "[ARG...]", false);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("~kfKCu7\u0002If!7}&K", options0, true);
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(32, "org.apache.commons.cli.help.TextStyle", "V=J[,c=L .a'b/", (Options) null, "org.apache.commons.cli.help.TextStyle");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      HelpFormatter.builder();
      // Undeclared exception!
      try { 
        helpFormatter0.createPadding((-1441));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "";
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "", options0, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("`RmJ>uQJ");
      Options options0 = new Options();
      helpFormatter0.printOptions(mockPrintWriter0, (-564), options0, 0, 0);
      helpFormatter0.defaultSyntaxPrefix = "]";
      helpFormatter0.setLeftPadding((-1998));
      helpFormatter0.getOptPrefix();
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      helpFormatter0.defaultWidth = 0;
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setPrintWriter(mockPrintWriter0);
      helpFormatter_Builder2.setShowDeprecated(true);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder2.setShowDeprecated(false);
      helpFormatter_Builder3.get();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("5Fa/X:g7wBq2$I=", options0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.printHelp("i[I6Yg#c$Dw", "i[I6Yg#c$Dw", options0, "y{`N", false);
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      MockFileOutputStream mockFileOutputStream0 = new MockFileOutputStream("ziY_g", true);
      MockPrintStream mockPrintStream0 = new MockPrintStream(mockFileOutputStream0);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockPrintStream0);
      helpFormatter_Builder0.setPrintWriter(mockPrintWriter0);
      helpFormatter0.getLongOptPrefix();
      helpFormatter0.setSyntaxPrefix("--");
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.createPadding(0);
      StringBuffer stringBuffer0 = new StringBuffer(3);
      Options options0 = new Options();
      StringBuffer stringBuffer1 = helpFormatter0.renderOptions(stringBuffer0, 0, options0, 1, 0);
      StringBuffer stringBuffer2 = helpFormatter0.renderWrappedText(stringBuffer1, 0, 0, "");
      helpFormatter0.renderOptions(stringBuffer2, 2597, options0, 0, 3767);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultLongOptPrefix = "";
      Options options0 = new Options();
      options0.helpOptions();
      Options options1 = new Options();
      options1.helpOptions();
      options1.hasLongOption("S.2%M%ZNNSkwJkZN");
      Options options2 = options0.addOptions(options1);
      helpFormatter0.printHelp(69, "   ", "   ", options0, "   ", true);
      helpFormatter0.getArgName();
      helpFormatter0.getOptPrefix();
      helpFormatter0.printHelp("arg", options1);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(728, "", "]", options2, "", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", "[Deprecated] ", (Options) null, "", false);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(false);
      helpFormatter_Builder1.get();
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated((Function<Option, String>) null);
      helpFormatter_Builder2.setShowDeprecated((Function<Option, String>) null);
      Options options0 = new Options();
      helpFormatter_Builder2.setShowDeprecated((Function<Option, String>) null);
      helpFormatter0.printHelp("$1)&giiR{w4,ppFN:", options0);
      helpFormatter_Builder2.setShowDeprecated((Function<Option, String>) null);
      helpFormatter0.getNewLine();
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      String string0 = "";
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp("", options0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      byte[] byteArray0 = new byte[3];
      byteArray0[0] = (byte)10;
      byteArray0[1] = (byte)107;
      byteArray0[2] = (byte)0;
      FileSystemHandling.appendDataToFile((EvoSuiteFile) null, byteArray0);
      FileSystemHandling.shouldThrowIOException((EvoSuiteFile) null);
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Options options0 = new Options();
      helpFormatter0.appendOptions((BufferedWriter) null, 23, options0, 23, 23);
      helpFormatter0.getLongOptPrefix();
      helpFormatter0.getArgName();
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setNewLine("");
      helpFormatter0.defaultDescPad = 0;
      helpFormatter0.setOptPrefix("yv)Q7I:Dk|xj3#.Li^");
      helpFormatter0.getOptionComparator();
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setDescPadding((-1247));
      MockPrintWriter mockPrintWriter0 = null;
      try {
        mockPrintWriter0 = new MockPrintWriter("usage: ", "<6?");
        fail("Expecting exception: UnsupportedEncodingException");
      
      } catch(Throwable e) {
         //
         // <6?
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockPrintWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test78()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      StringBuffer stringBuffer0 = new StringBuffer();
      helpFormatter0.renderWrappedText(stringBuffer0, 637, 637, "@(fO[y[");
  }

  @Test(timeout = 4000)
  public void test79()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringWriter stringWriter0 = new StringWriter(3);
      StringWriter stringWriter1 = stringWriter0.append((CharSequence) "-");
      StringBuffer stringBuffer0 = stringWriter1.getBuffer();
      Options options0 = new Options();
      StringBuffer stringBuffer1 = helpFormatter0.renderOptions(stringBuffer0, 0, options0, 0, 0);
      helpFormatter0.renderOptions(stringBuffer1, 0, options0, 0, 374);
  }

  @Test(timeout = 4000)
  public void test80()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.defaultSyntaxPrefix = "$VALUES";
      helpFormatter0.getNewLine();
      helpFormatter0.getNewLine();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) null, (-980), "b9", "b9", options0, (-980), 0, "$VALUES");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test81()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter0.setOptPrefix("");
  }

  @Test(timeout = 4000)
  public void test82()  throws Throwable  {
      HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setLeftPadding(0);
  }

  @Test(timeout = 4000)
  public void test83()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) "-");
      helpFormatter0.renderWrappedText(stringBuffer0, 1, 1, "Threshold must not be negative");
  }

  @Test(timeout = 4000)
  public void test84()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      StringBuffer stringBuffer0 = new StringBuffer((CharSequence) " ");
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.renderOptions(stringBuffer0, 0, options0, 0, 0);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test85()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      ByteArrayOutputStream byteArrayOutputStream0 = new ByteArrayOutputStream(74);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(byteArrayOutputStream0, false);
      Options options0 = new Options();
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 3556, "T|6hb4i6L]wp%gN(q(", "T|6hb4i6L]wp%gN(q(", options0, 3556, 3556, "T|6hb4i6L]wp%gN(q(");
  }

  @Test(timeout = 4000)
  public void test86()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      helpFormatter_Builder0.setShowSince(false);
      helpFormatter0.getOptPrefix();
      helpFormatter0.getLongOptSeparator();
      helpFormatter0.getLongOptPrefix();
      helpFormatter0.setArgName("--");
      helpFormatter0.createPadding(5);
  }

  @Test(timeout = 4000)
  public void test87()  throws Throwable  {
    Future<?> future = executor.submit(new Runnable(){ 
            @Override public void run() { 
          HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
          boolean boolean0 = false;
          helpFormatter_Builder0.setShowDeprecated(false);
          HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
          helpFormatter0.getNewLine();
          helpFormatter0.rtrim("\n");
          FileDescriptor fileDescriptor0 = new FileDescriptor();
          MockFileOutputStream mockFileOutputStream0 = null;
          try {
            mockFileOutputStream0 = new MockFileOutputStream(fileDescriptor0);
            fail("Expecting exception: SecurityException");
          
          } catch(SecurityException e) {
             //
             // Security manager blocks (\"java.lang.RuntimePermission\" \"writeFileDescriptor\")
             // java.lang.Thread.getStackTrace(Thread.java:1564)
             // org.evosuite.runtime.sandbox.MSecurityManager.checkPermission(MSecurityManager.java:434)
             // java.lang.SecurityManager.checkWrite(SecurityManager.java:954)
             // java.io.FileOutputStream.<init>(FileOutputStream.java:245)
             // org.evosuite.runtime.mock.java.io.MockFileOutputStream.<init>(MockFileOutputStream.java:114)
             // sun.reflect.GeneratedConstructorAccessor72.newInstance(Unknown Source)
             // sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
             // java.lang.reflect.Constructor.newInstance(Constructor.java:423)
             // org.evosuite.testcase.statements.ConstructorStatement$1.execute(ConstructorStatement.java:233)
             // org.evosuite.testcase.statements.AbstractStatement.exceptionHandler(AbstractStatement.java:169)
             // org.evosuite.testcase.statements.ConstructorStatement.execute(ConstructorStatement.java:188)
             // org.evosuite.testcase.execution.TestRunnable.executeStatements(TestRunnable.java:307)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:213)
             // org.evosuite.testcase.execution.TestRunnable.call(TestRunnable.java:55)
             // java.util.concurrent.FutureTask.run(FutureTask.java:266)
             // java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
             // java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
             // java.lang.Thread.run(Thread.java:750)
             //
             verifyException("org.evosuite.runtime.sandbox.MSecurityManager", e);
          }
      } 
    });
    future.get(4000, TimeUnit.MILLISECONDS);
  }

  @Test(timeout = 4000)
  public void test88()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      helpFormatter0.setOptPrefix("org.apache.commons.cli.HelpFormatter");
      Options options0 = new Options();
      Option option0 = new Option((String) null, "\n");
      option0.equals(helpFormatter0);
      Options options1 = options0.addOption(option0);
      options0.getMatchingOptions("org.apache.commons.cli.HelpFormatter");
      FileSystemHandling.shouldAllThrowIOExceptions();
      helpFormatter0.printHelp("org.apache.commons.cli.HelpFormatter", options0);
      helpFormatter0.setLongOptSeparator("org.apache.commons.text.similarity.CosineDistance");
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/Users/anthonykap/Documents/GitHub/commons-cli");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "");
      String string0 = "h6DHBkdOtTdmz";
      helpFormatter0.printHelp((-1), "org.apache.commons.text.similarity.CosineDistance", "org.apache.commons.text.similarity.CosineDistance", options1, "h6DHBkdOtTdmz", true);
      int int0 = 1865;
      String string1 = "Fcn*ce4#kP^trPi";
      helpFormatter0.printHelp(1865, "org.apache.commons.text.lookup.DnsStringLookup", "Fcn*ce4#kP^trPi", options1, "!j4i.'-|}h", false);
      MockFile mockFile0 = new MockFile("arg");
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(mockFile0);
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 1865, (String) null, "org.apache.commons.text.lookup.DnsStringLookup", options1, (-271), 0, "h6DHBkdOtTdmz");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test89()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(true);
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated((Function<Option, String>) null);
      HelpFormatter.Builder helpFormatter_Builder3 = helpFormatter_Builder0.setShowDeprecated((Function<Option, String>) null);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("cmdLineSyntax not provided");
      Locale locale0 = Locale.ROOT;
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("/Users/anthonykap/Documents/GitHub/commons-cli");
      FileSystemHandling.createFolder(evoSuiteFile0);
      helpFormatter_Builder0.setShowDeprecated((Function<Option, String>) null);
      PrintWriter printWriter0 = mockPrintWriter0.format(locale0, "cmdLineSyntax not provided", (Object[]) null);
      helpFormatter_Builder2.setPrintWriter(printWriter0);
      HelpFormatter.Builder helpFormatter_Builder4 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder3.get();
      Options options0 = new Options();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 32, "jID7", options0);
      helpFormatter0.printHelp("jID7", options0, true);
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(1);
      CharArrayWriter charArrayWriter1 = charArrayWriter0.append((CharSequence) " ");
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 32, "/V(V4D/", "org.apache.commons.text.lookup.AbstractStringLookup", options0, 20, 0, "/V(V4D/", true);
      options0.hasLongOption("arg");
      // Undeclared exception!
      try { 
        charArrayWriter1.append((CharSequence) "--", 32, 0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test90()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowSince(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter("B,VwvPhA}!Sg");
      String string0 = " | ";
      Object[] objectArray0 = new Object[7];
      objectArray0[0] = (Object) " | ";
      objectArray0[1] = (Object) helpFormatter_Builder0;
      objectArray0[3] = (Object) helpFormatter_Builder1;
      objectArray0[4] = (Object) helpFormatter_Builder1;
      objectArray0[5] = (Object) helpFormatter0;
      PrintWriter printWriter0 = mockPrintWriter0.format(" | ", objectArray0);
      int int0 = 32;
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp(printWriter0, 32, "B,VwvPhA}!Sg", " | ", options0, 32, 32, "B,VwvPhA}!Sg", false);
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test91()  throws Throwable  {
      HelpFormatter.builder();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      StringBuffer stringBuffer0 = new StringBuffer(3);
      helpFormatter0.renderWrappedText(stringBuffer0, (-2318), (-2318), "E ");
      char[] charArray0 = new char[8];
      charArray0[0] = '';
      charArray0[1] = '';
      charArray0[2] = '';
      charArray0[3] = '';
      charArray0[4] = '';
      charArray0[5] = '';
      charArray0[6] = '';
      charArray0[7] = '';
      Options options0 = new Options();
  }

  @Test(timeout = 4000)
  public void test92()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      StringWriter stringWriter0 = new StringWriter();
      StringWriter stringWriter1 = new StringWriter(1);
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(stringWriter1, false);
      stringWriter1.append('[');
      helpFormatter1.printUsage((PrintWriter) mockPrintWriter0, (-1177), "cmdLineSyntax not provided");
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      stringWriter1.append((CharSequence) "\n");
      helpFormatter_Builder0.setShowDeprecated(function0);
      helpFormatter1.getSyntaxPrefix();
      Options options0 = new Options();
      helpFormatter0.printHelp((PrintWriter) mockPrintWriter0, 468, "initialList", "arg", options0, 1, 1, "org.apache.commons.io.filefilter.IOFileFilter", true);
      helpFormatter1.getOptPrefix();
      helpFormatter1.printHelp("usage: ", "initialList", options0, "initialList", true);
  }

  @Test(timeout = 4000)
  public void test93()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = helpFormatter_Builder0.get();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      Options options0 = new Options();
      helpFormatter0.printHelp(3, "-", "\n", options0, "arg");
      helpFormatter1.setLeftPadding(1);
      int int0 = 0;
      helpFormatter1.renderOptions((StringBuffer) null, 0, options0, 39, 0);
      helpFormatter0.setArgName(">7y4l9");
      helpFormatter0.getWidth();
      PrintWriter printWriter0 = null;
      // Undeclared exception!
      try { 
        helpFormatter0.printWrapped((PrintWriter) null, 0, "arg");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test94()  throws Throwable  {
      HelpFormatter helpFormatter0 = new HelpFormatter();
      assertEquals(3, helpFormatter0.defaultDescPad);
      
      Options options0 = new Options();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("m", "#");
      OptionGroup optionGroup1 = optionGroup0.addOption(option0);
      options0.addOptionGroup(optionGroup1);
      options0.hasOption("");
      helpFormatter0.printHelp("BJC:}Xgx'[%Uq'{R'0~", "#", options0, "", false);
      assertEquals(1, helpFormatter0.getLeftPadding());
      assertEquals("usage: ", helpFormatter0.getSyntaxPrefix());
  }

  @Test(timeout = 4000)
  public void test95()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      HelpFormatter helpFormatter0 = helpFormatter_Builder1.get();
      helpFormatter_Builder0.get();
      helpFormatter0.setLongOptPrefix("{]~ea)sHQRMR");
      helpFormatter_Builder1.get();
      CharArrayWriter charArrayWriter0 = new CharArrayWriter(74);
      CharArrayWriter charArrayWriter1 = charArrayWriter0.append((CharSequence) " ");
      // Undeclared exception!
      try { 
        charArrayWriter1.append((CharSequence) "--", 1, 0);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test96()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = new HelpFormatter.Builder();
      HelpFormatter helpFormatter0 = new HelpFormatter();
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      helpFormatter0.setOptionComparator(comparator0);
      helpFormatter0.getWidth();
      Options options0 = new Options();
      // Undeclared exception!
      try { 
        helpFormatter0.printHelp((String) null, "1kvCrCSGjI", options0, (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // cmdLineSyntax not provided
         //
         verifyException("org.apache.commons.cli.HelpFormatter", e);
      }
  }

  @Test(timeout = 4000)
  public void test97()  throws Throwable  {
      HelpFormatter.Builder helpFormatter_Builder0 = HelpFormatter.builder();
      Function<Option, String> function0 = (Function<Option, String>) mock(Function.class, new ViolatedAssumptionAnswer());
      HelpFormatter.Builder helpFormatter_Builder1 = helpFormatter_Builder0.setShowDeprecated(function0);
      boolean boolean0 = true;
      HelpFormatter.Builder helpFormatter_Builder2 = helpFormatter_Builder1.setShowDeprecated(true);
      helpFormatter_Builder2.setShowDeprecated(true);
      HelpFormatter helpFormatter0 = helpFormatter_Builder2.get();
      helpFormatter0.getDescPadding();
      Comparator<Option> comparator0 = helpFormatter0.getOptionComparator();
      HelpFormatter helpFormatter1 = helpFormatter_Builder0.get();
      helpFormatter0.setOptionComparator(comparator0);
      HelpFormatter helpFormatter2 = helpFormatter_Builder0.get();
      StringWriter stringWriter0 = new StringWriter();
      MockPrintWriter mockPrintWriter0 = new MockPrintWriter(stringWriter0, true);
      mockPrintWriter0.flush();
      Options options0 = new Options();
      helpFormatter0.printUsage((PrintWriter) mockPrintWriter0, 0, "!I$a(pDD GWq_Loz7", options0);
      helpFormatter1.setLongOptSeparator("\n");
      helpFormatter0.getWidth();
      helpFormatter0.printHelp(3, " ", "wildcard", options0, "wildcard", true);
      helpFormatter0.setSyntaxPrefix("");
      helpFormatter1.printHelp(helpFormatter0.defaultLeftPad, helpFormatter0.DEFAULT_OPT_PREFIX, helpFormatter0.DEFAULT_LONG_OPT_SEPARATOR, options0, helpFormatter2.defaultArgName, boolean0);
  }
}
